name: deploy ExpenseLens to development environment
on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ECR_LOGIN_SERVER }}
          username: ${{ secrets.ECR_USERNAME }}
          password: ${{ secrets.ECR_PASSWORD }}
      - run: |
          docker build ./src/BackendService/Dockerfile -t ${{ secrets.ECR_LOGIN_SERVER }}/expense-lens-service:${{ github.sha }}
          docker push ${{ secrets.ECR_LOGIN_SERVER }}/expense-lens-service:${{ github.sha }}
