name: Deploy ExpenseLens to development environment
on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  build-function:
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build Azure Function and Zip
        run: |
          dotnet build src/Functions/Functions.csproj -c Release -o ./publish -p:DeployOnBuild=true -p:'DeployTarget=Package;CreatePackageOnPublish=true'
          cd publish
          zip -r ../ExpenseLensFunctions.zip .
          cd ..

      - name: Upload to storage using CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.FUNCTION_STORAGE_ACCOUNT_NAME }} -d 'function' -s . --pattern "*.zip"
